language: node_js
node_js:
- 8.11.2
deploy:
  provider: heroku
  api_key:
    secure: VUBklnm3KYwiK888FdwGxLDwhhpODZR72KQXqripcFO58gG+wS9VlI/SgGP8BA5L3+HDZagJgGligIGOIuFEhR3GlgqElv0xrabMev4uZrgsasZDKHRfPmd70bBfBf7snBeEqfomRP+a5K0Y+vj0xbD01/LCknnmxMIyx9YwKKpTaOWh5C/9bswfCVgQ9bRzTagtdh7DqXpWB8fXcRYsyNTXsjDky+CXASO5KaGUzJD7rezDyH3BMVawvS3PWNOPvCWUloSCFkJk2dLcp5gidEMxW8fGr4mu5yUPCY3Spu1ac2yRQAZsAon0MeS5kc+TyRQUryfnO9+clS/8sD3jWQYC1Xnf98qCswF4YyWsdxoP3OHphIpNHvMTHXd0yNw6cvl1uw7WrP6YwxANODM/OQuV/ZzAOERwSGP6gIuR9bMjmZ/3EeIAFoZlCrFuHfVNXhVXxsA70j+lxj4k7bo2ybW0wUw/SPb3IU7KLLvbDhhUiWKoJCLBTHeyFlhV3L+VscvJgwnwPh4RunLrgggvHS5dNCeySsf+okJvVECq5vj16AK18VSZkulrIjTUXSUp/IS6bGrE9GMNJ63pO/Xchne82mDBwNEkOqGEFwr/gy5+VijSmufGFJqJ+Ufc5P2bvg6AFaIJuSHcUSBhgfh8Hg0GynvxM1XMAGp4eqMM/yg=
  app: heroku-travis-test-01
  on:
    repo: andrico1234/heroku-travis-test
