language: node_js
node_js:
- 8.11.2

deploy:
  provider: heroku
  api_key:
    secure: lu5XTzQIN7sZ1T49RFnYZ4F15mOdBnAAeipM1LANYuzWLdzpkeHHIJBmz8/iWyl5PzWtCteXoeIS6UY4i2fZqGlv/ks8RMCc4yqIK9TEthIc9K4c1EO3cZh/nT7Hz6eqUWXAHRYx1DdHrTYymJeiv7atwP9K02nCsIOXcpwj/uJ3bh2vOlKZWIndD8CiTOIXpocoKKNO+Ux1Ja+QK6W2WoUVzAXbgf4rqz4liofyLAIsAjJatcDTxQ413rmQDLKxoo3px05uEGIjcKis2gK8X50XPf4iMfUhuHPlxDO8GDMurjf30WQLA7IinQOFrLdPctPjsJRhSBc71YtP2K7FoKPGBKSkEx7bkpZmdWUTMfLLKmWTh9637zZJIujuJ9rBwj+vnJ1oVxhpsAAApLDuZLCBJEoTooDNc83uILwvtm/z3rOqEoubquK3hoS3ft3Hhi8IBGcQKA/V/u145UxMVndQ+GS7Jg177GswVfX2pwJsQt6tASvi4pEzXM+4VxnG9vgOlVLEgM1CVCPdd87zahFs3xbmPTlMPVDnVKIpdOQRh3U3z+zAbh31w2QGjld08oIzCJkLQBcXAY4mrfmngWeQ4LYZyOQXNoNvs1nREW7pbGEEIdmIETYp+aXjpeCO3dc4L6pCIumy9/GwRpp6Yt0EH7A1JS08mTB0jB72sIs=
