language: node_js
node_js:
- 8.11.2

deploy:
  provider: heroku
  api_key:
    secure: g3gj25vI58r48P63EDK5fqWKM4fXkKX2ctXRvZki7GBUkHmByZ36v0fU/jEOcu9dBJNPnso4up57Rgr9lfil9jbKeWp1ktiVOCR6d5CuCxg+GTgS7Roq0SLjzvkhRTEvFhq5FxpEO8qD3zQzMtnv0YKB7nqBeJrwIxnxsS0zAscq5JS2HslcS1sBfd3CxhRUHZMPFBXXFwKB+RB6ac92BGOmuVHnULhuI0rgvSvKlJkPxsdJV/7vtQNXm+DfKUydtEg3XK6vvvl91XQbFI1Uexq7YQrAYV4TK++bEouXKjgQY8q+S6A/v10JqMwC6dUzY/cEHtC1EIAFRd9ARSIaFU7CC/+s6PfkxioOtMwM0cmZUg7xLsnT9Pgiqb8litGdppmuuVUwoBTPes5hyWRcVeyQ3Heb03w6PVHTeSE+2DqtS6ZWme8pYsTo4/XwLy7Hb3jKVIQMyLMykDsuPoGarUMJ9cMz1xMToI9H3kXOozcq8GFlBDI8c7+/ouiWW+C0JJNLOqO1q7Mq9bBZnzbbze+pipa21ydD5Qs9k1r+5ptlQ2HWQukrc/y6MNc4jngLetR2vLetp+l+WuDVDei1nRvi3olyejfhoei8oVOAv40XYB2f0xmOQxMYzLMQYHsbyXhHkU+vsGHrHRcm6pST46fUvwIRNJ1Sq9eeiWWD27E=
  app: heroku-travis-test-01
  on:
    repo: andrico1234/heroku-travis-test
