language: node_js
node_js:
- 8.11.2
deploy:
  provider: heroku
  api_key:
    secure: o/2867UdXT7w0WhKgQoy/jRV32onn9hQ378++3n0Mc8CLIPzfBqr8jUk38zczqD6Z1mzYGDfWksLYwMouDtUWjO5aFzcX+OgcCRZfBOYssm/9t5lxlUyu8O5OnS/OMFPX8QWlDwtpvtg2FhvbPNC/V/G3wkZ+Ut1KesqhNWiMfV9xg8WdrZEnhPCbZXbgVcL4aa8vK613VeRYNeGvAwGvkjQTyqDGNZomjSUcw3+Qu1VcZYeErMMylopTs7SNUWWTwepdKP3Iyzd0xpHeZ/QeOYZvrvLR0XZ/t1wpcKlPKPHLQFGhdGjlJc/HMTMjU4eqlHBSS94z3CmGLQ3y8Lwl2M4UPqkFbr/Hme9hMSptyMclnvZeSlHVR9EPdvCW00XVY5yShk6i4u/KGGnaMTc+/hVfToNT+u5O5cw83a8XJyhd5WkXLz4+W41AQ6f0VKn7LJIzH2Sy6cKZaYlVF4L1EMaOZGTEaRtrpRMuaJywNCbSASoxhVqCUlfLgwqoRKfOJY1av5gWq0AnoUmb5Kw9jPP1Y/F2+ZggtgyRqMItKJvgdZUTER0kG5gcJ8bI5YDnyQAfgThI41ukatzfbSevvi9m83+pLfcWgKje1F4jbyARNLdpXcFH8LWJHaPEF+a9lIuCh52NA7ZGikksYGdkKKlFfshvNsh6IM9jQruL8U=
  app: heroku-travis-test-01
  on:
    repo: andrico1234/heroku-travis-test
