language: node_js
node_js:
- 8.11.2

cache: yarn

install:
- yarn global add lerna jest now
- lerna bootstrap

deploy:
  - provider: script
    script: now --token ${NOW_TOKEN}
    skip_cleanup: true
