language: node_js
node_js:
- 8.11.2

deploy:
  provider: heroku
  api_key:
    secure: s40eqOdXJ+KZGa9aw6sID2pszC9KhEe4UH1eMa45mZRGFutYJXuYdXIGFTnmbpYGzxUteRAm1Dv38ZooJQ7yZTRTtHnXov6y32KV/qtknxO86JN43s/KZCscCpqBuHeKSOoC2/SNg6qOh9cJU58OcheFTSLBm7+py4apo8bl1tQWq8/ilYy/CcQxMfd+lJEi6B35dNIkrLmuvHKrGPPgsuI4eDqorzzf4QaJHvUKb0WyLjxZhruTZ3pMjBhAypaEfw+z1r+pOtBzQx3ObJt0sRTshq9mGkoNXC6X6W/3zV2oYKv2P/vBCCUVz3I7Pncr25KJkDAaPyqmC8br31DASiF6UQxBCog+iPjEVwpVYmagmCRZgp0+qnGRVzm+lu0v0Lx+zn85dQqT+HcFz0n17N88CIGbfkLR8sssIBYKj5Fs3LN6spB1Q0+O0RryGIEK2XhI/ll18BH9R5gM05DrspQG2cYUVMoxUAAlXysnYd0e0Rn044D3Hseixw6bPMlWVe64uuLflF0tYG3PFH0Y9NWFgNTaLwK5qzGcCmIdNalPeyb4offeACl18beslQhDqnpVQLZFJoNEB0TwBigGVGDcNAQg95HKdjQaM7l26Jw8seVXVvKmqVHKo1xz3gXtgvo0TwIAydqD888LdwC7HFP1jv+pW/4/OCzKzX4kbw0=
